language: c++
compiler: g++
os: windows
branch:
  only:
  - main
  - dev
install: cmake -G "MinGW Makefiles" -std=gnu++14 -DCMAKE_CXX_FLAGS="-O3" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -B cmake
script:
  - cmake --build cmake
  - ./build/voxelmade_tests.exe
